### ISSUE TITLE
24-bit LFSR value

### ISSUE THREAD

**Issue by ballifatih** [romulusae/romulus#1]
I was wondering whether the reference implementation is using the correct 24-bit LFSR for the Romulus-N3 variant.

Namely, the specification (v 1.2.) for N3 defines the reduction polynomial of LFSR as:

F_24(x) = x^24 + x^4 + x^3 + x + 1

Hence, the mask value would correspond to "1B" in hexadecimals. However, the value "95" is used instead, which would be correct according to the other 56-bit LFSR. The source file is:

Implementations/software/ref/Romulus-N3/encrypt.c

Could you confirm if this is a bug or am I missing something?

**Comment by mustafa-khairallah** [comment]
Thanks for your report and apologies for the delayed reply. You are right, the correct value should be 1B. I will fix this but for your information N3 is being dropped from the package in the algorithm update: https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/status-update-sep2020/Romulus-for-Round-3.pdf
